package com.tibudget.dto;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.tibudget.dto.MessageDto.MessageType;

public class MessagesDto implements Serializable {

	Map<String, List<MessageDto>> messages;

	public MessagesDto() {
		super();
		messages = new HashMap<>();
	}

	public MessagesDto(Iterable<MessageDto> msg) {
		this();
		for (MessageDto messageDto : msg) {
            List<MessageDto> thisMsg = messages.computeIfAbsent(messageDto.getFieldName(), k -> new ArrayList<>());
            thisMsg.add(messageDto);
		}
	}

	public boolean hasGlobalMessages() {
		return hasFieldMessages(null);
	}

	public Iterable<MessageDto> getGlobalMessages() {
		return getFieldMessages(null);
	}

	public Iterable<MessageDto> getAllMessages() {
		List<MessageDto> allMessages = new ArrayList<MessageDto>();
		for (List<MessageDto> messageDtos : messages.values()) {
			allMessages.addAll(messageDtos);
		}
		return allMessages;
	}

	public boolean hasFieldMessages(String fieldName) {
		return messages.get(fieldName) != null;
	}

	public Iterable<MessageDto> getFieldMessages(String fieldName) {
		return messages.get(fieldName);
	}
	
	public boolean hasMessageType(MessageType type) {
		for (List<MessageDto> messageDtos : messages.values()) {
			for (MessageDto messageDto : messageDtos) {
				if (messageDto.getType() == type) {
					return true;
				}
			}		
		}
		return false;
	}

	/**
	 * Autogenerated by eclipse IDE
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((messages == null) ? 0 : messages.hashCode());
		return result;
	}

	/**
	 * Autogenerated by eclipse IDE
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MessagesDto other = (MessagesDto) obj;
		if (messages == null) {
			if (other.messages != null)
				return false;
		} else if (!messages.equals(other.messages))
			return false;
		return true;
	}
}
