package com.tibudget.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

/**
 * Describes a recurring payment, such as a subscription, an installment plan, or any payment split over multiple periods.
 */
public class RecurringPaymentDto implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Time unit used to describe the recurrence frequency.
     */
    public enum RecurrenceUnit {
        DAY,
        WEEK,
        MONTH,
        YEAR
    }

    public enum State {
        /**
         * The recurring payment is active and will be processed even if the first payment has not yet been made.
         */
        ACTIVE,
        /**
         * The recurring payment is paused and will not be processed until it is resumed. It is not a cancellation.
         */
        PAUSED,
        /**
         * The recurring payment has ended and will not be processed anymore.
         */
        ENDED
    }

    /**
     * Unique identifier for this recurring payment within the associated account.
     * <p>
     * The collector can find or compute it using collected data.
     * This ID is used as a key for subsequent recurring payment updates.
     * The collector can retrieve the correct recurring payment using this ID.
     */
    private String id;

    /**
     * UUID generated by Tibu.
     * If you create a new recurring payment, generate one using
     * java.util.UUID.randomUUID().toString().
     * <p>
     * This UUID is stable across multiple collects.
     */
    private String uuid;

    /**
     * Unique identifier of the account associated with this recurring payment.
     */
    private String accountUuid;

    /**
     * Human readable label describing the recurring payment.
     * Example: "Amazon Prime", "Home insurance", "Mobile subscription".
     */
    private String label;

    /**
     * Expected recurring amount.
     * <p>
     * The currency must be the one associated with the account.
     * Can be null for variable amount recurring payments.
     */
    private Double expectedAmount;

    /**
     * Acceptable percentage variation for the expected amount.
     * <p>
     * This value represents a ratio, not a percentage.
     * <p>
     * Examples:
     * - 0.00 = no variation allowed (fixed amount)
     * - 0.05 = up to ±5% variation allowed
     * - 0.10 = up to ±10% variation allowed
     * <p>
     * If the recurring payment amount is expected to be fixed,
     * this value must be set to 0.00.
     * <p>
     * If the detected amount exceeds this variation,
     * the application may notify the user.
     * <p>
     * Can be null if no variation monitoring is required.
     */
    private Double acceptableAmountVariationRatio;

    /**
     * End date of the recurring payment.
     * <p>
     * Null means that the recurring payment has no known end date
     * and is considered ongoing.
     */
    private Date dateEnd;

    /**
     * Start date of the recurring payment if known (sometimes the information is not avaiable, in this case just set the state accordingly).
     * <p>
     * This date represents when the recurring payment started
     * or is expected to start.
     */
    private Date dateStart;

    /**
     * Recurrence interval.
     * <p>
     * Every X units.
     * Example: every 1 MONTH, every 2 WEEKS.
     */
    private int recurrenceInterval;

    /**
     * Unit associated with the recurrence interval.
     */
    private RecurrenceUnit recurrenceUnit;

    /**
     * Indicates the current state of the recurring payment.
     * If PAUSED you can indicates the expected resume date if known.
     */
    private State state;

    /**
     * Date when the recurring payment is expected to resume.
     * <p>
     * Can be null if the resume date is unknown
     * or if the pause is considered indefinite.
     */
    private Date resumeDate;

    /**
     * Default constructor.
     */
    public RecurringPaymentDto() {
        this(null, null, null);
    }

    public RecurringPaymentDto(
            String id,
            String uuid,
            String accountUuid) {
        this(id, uuid, accountUuid, null, null, null, null, null, 1, null, State.ACTIVE, null);
    }

    /**
     * Full constructor.
     */
    public RecurringPaymentDto(
            String id,
            String uuid,
            String accountUuid,
            String label,
            Double expectedAmount,
            Double acceptableAmountVariationRatio,
            Date dateStart,
            Date dateEnd,
            int recurrenceInterval,
            RecurrenceUnit recurrenceUnit,
            State state,
            Date resumeDate
    ) {
        this.id = id;
        this.uuid = uuid;
        this.accountUuid = accountUuid;
        this.label = label;
        this.expectedAmount = expectedAmount;
        this.acceptableAmountVariationRatio = acceptableAmountVariationRatio;
        this.dateStart = dateStart;
        this.dateEnd = dateEnd;
        this.recurrenceInterval = recurrenceInterval;
        this.recurrenceUnit = recurrenceUnit;
        this.state = state;
        this.resumeDate = resumeDate;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getAccountUuid() {
        return accountUuid;
    }

    public void setAccountUuid(String accountUuid) {
        this.accountUuid = accountUuid;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public Double getExpectedAmount() {
        return expectedAmount;
    }

    public void setExpectedAmount(Double expectedAmount) {
        this.expectedAmount = expectedAmount;
    }

    public Double getAcceptableAmountVariationRatio() {
        return acceptableAmountVariationRatio;
    }

    public void setAcceptableAmountVariationRatio(Double acceptableAmountVariationRatio) {
        this.acceptableAmountVariationRatio = acceptableAmountVariationRatio;
    }

    public Date getDateEnd() {
        return dateEnd;
    }

    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }

    public Date getDateStart() {
        return dateStart;
    }

    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }

    public int getRecurrenceInterval() {
        return recurrenceInterval;
    }

    public void setRecurrenceInterval(int recurrenceInterval) {
        this.recurrenceInterval = recurrenceInterval;
    }

    public RecurrenceUnit getRecurrenceUnit() {
        return recurrenceUnit;
    }

    public void setRecurrenceUnit(RecurrenceUnit recurrenceUnit) {
        this.recurrenceUnit = recurrenceUnit;
    }

    public State getState() {
        return state;
    }

    public void setState(State state) {
        this.state = state;
    }

    public Date getResumeDate() {
        return resumeDate;
    }

    public void setResumeDate(Date resumeDate) {
        this.resumeDate = resumeDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RecurringPaymentDto)) return false;
        RecurringPaymentDto that = (RecurringPaymentDto) o;
        return Objects.equals(uuid, that.uuid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(uuid);
    }

    @Override
    public String toString() {
        return "RecurringPaymentDto{" +
                "id='" + id + '\'' +
                ", uuid='" + uuid + '\'' +
                ", accountUuid='" + accountUuid + '\'' +
                ", label='" + label + '\'' +
                ", expectedAmount=" + expectedAmount +
                ", dateStart=" + dateStart +
                ", dateEnd=" + dateEnd +
                ", recurrenceInterval=" + recurrenceInterval +
                ", recurrenceUnit=" + recurrenceUnit +
                ", state=" + state +
                ", resumeDate=" + resumeDate +
                '}';
    }
}
