package com.tibudget.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

/**
 * Represents a recurring payment, such as a subscription, an installment plan,
 * or any payment split over multiple periods.
 */
public class RecurringPaymentDto implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Time unit used to describe the recurrence frequency.
     */
    public enum RecurrenceUnit {
        DAY,
        WEEK,
        MONTH,
        YEAR
    }

    /**
     * Current state of a recurring payment.
     */
    public enum State {
        /**
         * The recurring payment is active and will be processed even if the first
         * payment has not yet been made.
         */
        ACTIVE,
        /**
         * The recurring payment is paused and will not be processed until it is
         * resumed. This is not a cancellation.
         */
        PAUSED,
        /**
         * The recurring payment has ended and will not be processed anymore.
         */
        ENDED
    }

    /**
     * Unique identifier for this recurring payment within the associated account.
     * <p>
     * The collector can find or compute it using collected data.
     * This ID is used as a key for subsequent recurring payment updates.
     */
    private String id;

    /**
     * UUID generated by Tibu.
     * <p>
     * If you create a new recurring payment, generate one using
     * {@code java.util.UUID.randomUUID().toString()}.
     * This UUID is stable across multiple collects.
     */
    private String uuid;

    /**
     * Unique identifier of the account associated with this recurring payment.
     */
    private String accountUuid;

    /**
     * Human-readable label describing the recurring payment.
     * Example: {@code Amazon Prime}, {@code Home insurance}, {@code Mobile subscription}.
     */
    private String label;

    /**
     * Expected recurring amount.
     * <p>
     * The currency must be the one associated with the account.
     * Can be {@code null} for variable amount recurring payments.
     */
    private Double expectedAmount;

    /**
     * Acceptable percentage variation for the expected amount.
     * <p>
     * This value represents a ratio, not a percentage.
     * Examples:
     * <ul>
     *     <li>{@code 0.00} = no variation allowed (fixed amount)</li>
     *     <li>{@code 0.05} = up to ±5% variation allowed</li>
     *     <li>{@code 0.10} = up to ±10% variation allowed</li>
     * </ul>
     * If the recurring payment amount is expected to be fixed, this value must be
     * set to {@code 0.00}.
     * <p>
     * Can be {@code null} if no variation monitoring is required.
     */
    private Double acceptableAmountVariationRatio;

    /**
     * End date of the recurring payment.
     * <p>
     * {@code null} means that the recurring payment has no known end date and is
     * considered ongoing.
     */
    private Date dateEnd;

    /**
     * Start date of the recurring payment, if known.
     * <p>
     * If this information is not available, set the state accordingly.
     * This date represents when the recurring payment started or is expected to start.
     */
    private Date dateStart;

    /**
     * Recurrence interval.
     * <p>
     * Every X units, for example every 1 month or every 2 weeks.
     */
    private int recurrenceInterval;

    /**
     * Unit associated with the recurrence interval.
     */
    private RecurrenceUnit recurrenceUnit;

    /**
     * Indicates the current state of the recurring payment.
     * <p>
     * If the state is {@link State#PAUSED}, the expected resume date can be provided
     * if known.
     */
    private State state;

    /**
     * Date when the recurring payment is expected to resume.
     * <p>
     * Can be {@code null} if the resume date is unknown or if the pause is
     * considered indefinite.
     */
    private Date resumeDate;

    /**
     * Creates a new recurring payment with no initial data.
     */
    public RecurringPaymentDto() {
        this(null, null, null);
    }

    /**
     * Creates a recurring payment with the minimum required identifiers.
     *
     * @param id the identifier within the associated account
     * @param uuid the globally unique identifier
     * @param accountUuid the associated account UUID
     */
    public RecurringPaymentDto(
            String id,
            String uuid,
            String accountUuid) {
        this(id, uuid, accountUuid, null, null, null, null, null, 1, null, State.ACTIVE, null);
    }

    /**
     * Creates a recurring payment with all available fields.
     *
     * @param id the identifier within the associated account
     * @param uuid the globally unique identifier
     * @param accountUuid the associated account UUID
     * @param label the human-readable label
     * @param expectedAmount the expected recurring amount
     * @param acceptableAmountVariationRatio the acceptable amount variation ratio
     * @param dateStart the start date
     * @param dateEnd the end date
     * @param recurrenceInterval the recurrence interval
     * @param recurrenceUnit the recurrence unit
     * @param state the current state
     * @param resumeDate the expected resume date
     */
    public RecurringPaymentDto(
            String id,
            String uuid,
            String accountUuid,
            String label,
            Double expectedAmount,
            Double acceptableAmountVariationRatio,
            Date dateStart,
            Date dateEnd,
            int recurrenceInterval,
            RecurrenceUnit recurrenceUnit,
            State state,
            Date resumeDate
    ) {
        this.id = id;
        this.uuid = uuid;
        this.accountUuid = accountUuid;
        this.label = label;
        this.expectedAmount = expectedAmount;
        this.acceptableAmountVariationRatio = acceptableAmountVariationRatio;
        this.dateStart = dateStart;
        this.dateEnd = dateEnd;
        this.recurrenceInterval = recurrenceInterval;
        this.recurrenceUnit = recurrenceUnit;
        this.state = state;
        this.resumeDate = resumeDate;
    }

    /**
     * Returns the recurring payment identifier within the associated account.
     *
     * @return the recurring payment identifier
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the recurring payment identifier within the associated account.
     *
     * @param id the recurring payment identifier
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Returns the recurring payment UUID.
     *
     * @return the UUID
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets the recurring payment UUID.
     *
     * @param uuid the UUID
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * Returns the associated account UUID.
     *
     * @return the associated account UUID
     */
    public String getAccountUuid() {
        return accountUuid;
    }

    /**
     * Sets the associated account UUID.
     *
     * @param accountUuid the associated account UUID
     */
    public void setAccountUuid(String accountUuid) {
        this.accountUuid = accountUuid;
    }

    /**
     * Returns the human-readable label.
     *
     * @return the label
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the human-readable label.
     *
     * @param label the label
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * Returns the expected recurring amount.
     *
     * @return the expected amount
     */
    public Double getExpectedAmount() {
        return expectedAmount;
    }

    /**
     * Sets the expected recurring amount.
     *
     * @param expectedAmount the expected amount
     */
    public void setExpectedAmount(Double expectedAmount) {
        this.expectedAmount = expectedAmount;
    }

    /**
     * Returns the acceptable amount variation ratio.
     *
     * @return the acceptable variation ratio
     */
    public Double getAcceptableAmountVariationRatio() {
        return acceptableAmountVariationRatio;
    }

    /**
     * Sets the acceptable amount variation ratio.
     *
     * @param acceptableAmountVariationRatio the acceptable variation ratio
     */
    public void setAcceptableAmountVariationRatio(Double acceptableAmountVariationRatio) {
        this.acceptableAmountVariationRatio = acceptableAmountVariationRatio;
    }

    /**
     * Returns the end date of the recurring payment.
     *
     * @return the end date
     */
    public Date getDateEnd() {
        return dateEnd;
    }

    /**
     * Sets the end date of the recurring payment.
     *
     * @param dateEnd the end date
     */
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }

    /**
     * Returns the start date of the recurring payment.
     *
     * @return the start date
     */
    public Date getDateStart() {
        return dateStart;
    }

    /**
     * Sets the start date of the recurring payment.
     *
     * @param dateStart the start date
     */
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }

    /**
     * Returns the recurrence interval.
     *
     * @return the recurrence interval
     */
    public int getRecurrenceInterval() {
        return recurrenceInterval;
    }

    /**
     * Sets the recurrence interval.
     *
     * @param recurrenceInterval the recurrence interval
     */
    public void setRecurrenceInterval(int recurrenceInterval) {
        this.recurrenceInterval = recurrenceInterval;
    }

    /**
     * Returns the recurrence unit.
     *
     * @return the recurrence unit
     */
    public RecurrenceUnit getRecurrenceUnit() {
        return recurrenceUnit;
    }

    /**
     * Sets the recurrence unit.
     *
     * @param recurrenceUnit the recurrence unit
     */
    public void setRecurrenceUnit(RecurrenceUnit recurrenceUnit) {
        this.recurrenceUnit = recurrenceUnit;
    }

    /**
     * Returns the current state.
     *
     * @return the state
     */
    public State getState() {
        return state;
    }

    /**
     * Sets the current state.
     *
     * @param state the state
     */
    public void setState(State state) {
        this.state = state;
    }

    /**
     * Returns the expected resume date.
     *
     * @return the expected resume date
     */
    public Date getResumeDate() {
        return resumeDate;
    }

    /**
     * Sets the expected resume date.
     *
     * @param resumeDate the expected resume date
     */
    public void setResumeDate(Date resumeDate) {
        this.resumeDate = resumeDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RecurringPaymentDto)) return false;
        RecurringPaymentDto that = (RecurringPaymentDto) o;
        return Objects.equals(uuid, that.uuid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(uuid);
    }

    @Override
    public String toString() {
        return "RecurringPaymentDto{" +
                "id='" + id + '\'' +
                ", uuid='" + uuid + '\'' +
                ", accountUuid='" + accountUuid + '\'' +
                ", label='" + label + '\'' +
                ", expectedAmount=" + expectedAmount +
                ", dateStart=" + dateStart +
                ", dateEnd=" + dateEnd +
                ", recurrenceInterval=" + recurrenceInterval +
                ", recurrenceUnit=" + recurrenceUnit +
                ", state=" + state +
                ", resumeDate=" + resumeDate +
                '}';
    }
}
