package com.tibudget.dto;

import java.io.Serializable;

public class SearchOperationFilter implements Serializable {
	
	private static final long serialVersionUID = -2530535215186320105L;

	public enum FilterType {
		ACCOUNT, CATEGORY, LABEL, DATE_IMPORTED
	}
	
	private FilterType type;
	
	private String title;
	
	private Object value;

	public SearchOperationFilter(FilterType type, Object value, String title) {
		super();
		this.type = type;
		this.value = value;
		this.title = title;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public FilterType getType() {
		return type;
	}

	public void setType(FilterType type) {
		this.type = type;
	}

	public Object getValue() {
		return value;
	}

	public void setValue(Object value) {
		this.value = value;
	}

	/**
	 * Generated by Eclipse IDE
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((title == null) ? 0 : title.hashCode());
		result = prime * result + ((type == null) ? 0 : type.hashCode());
		result = prime * result + ((value == null) ? 0 : value.hashCode());
		return result;
	}

	/**
	 * Generated by Eclipse IDE
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SearchOperationFilter other = (SearchOperationFilter) obj;
		if (title == null) {
			if (other.title != null)
				return false;
		} else if (!title.equals(other.title))
			return false;
		if (type != other.type)
			return false;
		if (value == null) {
			if (other.value != null)
				return false;
		} else if (!value.equals(other.value))
			return false;
		return true;
	}
}
