package com.tibudget.api;

/**
 * Interface for retrieving One-Time Passwords (OTP) from various channels.
 */
public interface OTPProvider {

    /**
     * Defines the available OTP delivery channels.
     */
    enum Channel {
        /** Code sent via SMS */
        SMS,
        /** Code sent via email */
        EMAIL,
        /** Time-based One-Time Password (TOTP), typically generated by authenticator apps such as Google Authenticator, Authy, or Microsoft Authenticator */
        TOTP
    }

    /** Regular expression pattern for a 4-digit OTP */
    String PATTERN_4_DIGIT = "\\d{4}";
    /** Regular expression pattern for a 6-digit OTP */
    String PATTERN_6_DIGIT = "\\d{6}";

    /**
     * Retrieves an OTP based on the specified parameters.
     * <p>
     * WARNING: This method is synchronous, so it may take a few minutes to retrieve the code.
     *
     * @param channel The channel where the OTP is expected (e.g., SMS, Email, or TOTP).
     * @param keyword A keyword that must be present in the message containing the OTP, usually the brand or service sending the code.
     * @param pattern The expected format of the OTP. You can use predefined patterns such as {@link #PATTERN_6_DIGIT}.
     * @param prompt Message to display to the user
     * @return The OTP if found within a reasonable delay, or {@code null} if no matching code is available.
     */
    String getCode(Channel channel, String keyword, String pattern, String prompt);
}
